spring.application.name=lab06_he186170
server.port=8080

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=OrchidJWT
spring.datasource.username=test
spring.datasource.password=123456789

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7c6d3a8b91e2f4d6a7c8b9e1f
security.jwt.expiration-time=360000
